# Generated by Django 3.2.12 on 2022-03-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='menu_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restauracja_app.category')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
