# Generated by Django 3.2.12 on 2022-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0006_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='comment',
        ),
        migrations.AddField(
            model_name='reserve',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
