# Generated by Django 3.2.12 on 2022-03-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0007_auto_20220324_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='menu',
            new_name='meal',
        ),
    ]
