# Generated by Django 3.2.12 on 2022-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0008_rename_menu_comments_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=64),
        ),
    ]
