# Generated by Django 3.2.12 on 2022-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0009_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
