# Generated by Django 3.2.12 on 2022-03-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0011_auto_20220328_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderdetails',
        ),
    ]
