# Generated by Django 3.2.12 on 2022-04-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0013_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
