# Generated by Django 3.2.12 on 2022-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restauracja_app', '0015_reserve_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='realized',
            field=models.BooleanField(default=False, help_text='Nie'),
        ),
    ]
